---
title: "Descritiva Dados Groeneveld"
output: html_document
date: "2024-01-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE)
```

# Descritiva dados groenveld

Neste documento serão apresentadas as estatísticas descritivas dos dados
disponibilizados por Groeneveld (2006) para o desenvolvimento da sua LUT (lookup table)
disponiveis em https://www.nrc.gov/reading-rm/doc-collections/nuregs/knowledge/km0011/index.html
para download.

# Bibliotecas utilizadas

```{r}

library(dplyr)
library(janitor)
library(ggplot2)
library(ggpubr)
library(GGally)
library(gridExtra)

```


# Leitura da base

Base tratada a partir do pdf no codigo trata_base_groeneveld.R

```{r}
base_look_up = read.csv2("dados_groeneveld.csv")

base_look_up = base_look_up %>%
  select(-X)

head(base_look_up)
```

```{r}
# variaveis disponiveis na base

colnames(base_look_up)
```

# Medidas de dispersão Básicas

```{r}

summary(base_look_up)

sd(base_look_up$D_mm)
sd(base_look_up$L_mm)
sd(base_look_up$P_kpa)
sd(base_look_up$G)
sd(base_look_up$X_chf)
sd(base_look_up$DH_in)
sd(base_look_up$CHF)
sd(base_look_up$T_in)

```

