---
title: "descritiva_dados_zhao"
output: html_document
date: "2024-01-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE)
```


# Descritiva dados Zhao total e subresfriado


```{r}

library(dplyr)
library(janitor)
library(ggplot2)
library(ggpubr)
library(GGally)
library(gridExtra)

```


```{r}
base_chf_zhao = read.csv("../dados/dados_zhao.csv")

base_chf_zhao = janitor::clean_names(base_chf_zhao)

head(base_chf_zhao)
```

```{r}
# variaveis disponiveis na base

colnames(base_chf_zhao)
```

```{r}

base_sub = base_chf_zhao %>%
  filter(x_e_out < 0)

nrow(base_sub)


base_sub$P_kpa = base_sub$pressure_m_pa*1000
base_sub$CHF = base_sub$chf_exp_mw_m2*1000

write.csv(base_sub,"dados_modelagem_zhao.csv",row.names = FALSE)
  
```


## Medidas de dispersão Básicas

```{r}

base_sub %>%
  group_by(geometry) %>%
  count()

summary(base_sub)


sd(base_sub$d_h_mm)
sd(base_sub$length_mm)
sd(base_sub$P_kpa)
sd(base_sub$mass_flux_kg_m2_s)
sd(base_sub$x_e_out)
sd(base_sub$CHF)

```

## Medidas de dispersão Básicas

```{r}

summary(base_sub)


sd(base_sub$D_mm)
sd(base_sub$L_mm)
sd(base_sub$P_kpa)
sd(base_sub$G)
sd(base_sub$X_chf)
sd(base_sub$DH_in)
sd(base_sub$CHF)
sd(base_sub$T_in)

```

#distribuicao das referencias

```{r}

referencias = base_sub %>%
  group_by(Reference) %>% 
  count() %>%
  arrange(desc(n))

referencias

```


## Graficos Variável x CHF

```{r}

# pressao

ggplot(base_sub) +
  geom_point(aes(x = P_kpa, y = CHF))

p = ggplot() +
  geom_point(aes(x = base_sub$P_kpa, y = base_sub$CHF)) +
  geom_smooth(aes(x = seq(100,20680), y = seq(100,20680) * -0.1875 + 6975.3103,colour = "CHF = 6975.3105 - 18.75 * Pressure"))+
  geom_smooth(aes(x = seq(100,20680), y = seq(100,20680) * -0.2 + 6000,colour = "CHF = 6000 - 0.2 * Pressure"))+
  geom_smooth(aes(x = seq(100,20680), y = seq(100,20680) * -0.17 + 7500,colour = "CHF = 7500 - 0.17 * Pressure")) +
  theme(legend.position = "bottom") +
  labs(color=NULL) +
  xlab("Pressure") +
  ylab("CHF")

p = ggplot(base_sub) +
  geom_point(aes(P_kpa, y = CHF)) +
  geom_smooth(aes(P_kpa, y = CHF), method = lm, formula = "y ~ x", se = TRUE) +
  xlab("Pressure") +
  ylab("CHF")

p

lm_example = lm(data = base_sub,
   CHF ~ P_kpa)

summary(lm_example)
confint(lm_example,level = 0.90)

library(stargazer)

stargazer(lm_example, ci=TRUE, ci.level=0.95)

jpeg("../Subcooled_CHF/dados/dados_pressao_gro.jpeg",width = 17,height = 10.51,units = "cm",res = 300)
p
dev.off()

p = ggplot(base_sub,aes(x = P_kpa, y = CHF)) +
  geom_point() +
  geom_smooth(method = "gam",formula = y ~ s(x,bs = 'cr',k = 20),aes(colour = "GAM")) +
  geom_smooth(formula = "y~x", method = "glm", aes(colour = "GLM")) +
    theme(legend.position = "bottom") +
  labs(color=NULL) +
  xlab("Pressure") +
  ylab("CHF")

jpeg("../Subcooled_CHF/dados/gam_glm_pressao.jpeg",width = 17,height = 10.51,units = "cm",res = 300)
p
dev.off()

# fluxo

ggplot(base_sub,aes(x = mass_flux_kg_m2_s, y = CHF)) +
  geom_point() +
  geom_smooth(formula,aes(colour = "GAM")) +
  geom_smooth(formula = "y~x", method = "glm", aes(colour = "GLM")) +
  


# X

ggplot(base_sub) +
  geom_point(aes(x = x_e_out, y = CHF))

ggplot(base_sub,aes(x = x_e_out, y = CHF)) +
  geom_point() +
  geom_smooth() +
  geom_smooth(formula = "y~x", method = "lm") 

# diametro

ggplot(base_sub) +
  geom_point(aes(x = d_h_mm, y = CHF))

# L comprimento

ggplot(base_sub) +
  geom_point(aes(x = length_mm, y = CHF))


```

## Plot 2x2 das variáveis

```{r}
library(GGally)

colnames(base_sub) = c("id","Reference","Geometry","P_mpa","G","X_chf","D_e_mm","D_mm","L_mm","CHF_mw","P_kpa","CHF")

# plot 2 a 2 das variaveis
plot_pair = base_sub %>%
  dplyr::select(D_mm,
                L_mm,
                P_kpa,
                G,
                X_chf,
                CHF
  ) %>%
  ggpairs(upper = list(continuous = wrap(ggally_cor, display_grid = FALSE)),
          lower = list(continuous = wrap("points",
                                         color = "navy",
                                         alpha = 1/10,
                                         size = 0.1)),
          proportions = "auto") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
  

jpeg("../Subcooled_CHF/dados/dados_pares_sub_zhao.jpeg",width = 17,height = 10.51,units = "cm",res = 300)
plot_pair
dev.off()

```

## Distribuicao da Variável Resposta

```{r}
library(hrbrthemes)

p1 = ggplot(base_sub) +
  geom_density(aes(x = CHF),fill="#69b3a2", color="#e9ecef", alpha=0.8) +
    theme_ipsum()#+
 # xlim(0, max(base_sub$CHF))

p1

p2 = ggqqplot(base_sub$CHF) +
  labs(y = "CHF", x = "Theoretical",title ="Shapiro Wilk Normality Test P-value < 2.2e-16" )
p2

require(EnvStats)
library(GeneralizedHyperbolic)

gama = qqPlot(base_sub$CHF, dist = "gamma", estimate.params = TRUE, add.line = TRUE)

lognormal = qqPlot(base_sub$CHF, dist = "lnorm", estimate.params = TRUE, add.line = TRUE)

g = arrangeGrob(  p1,
  p2,
  nrow = 1,
  ncol = 2)

jpeg("../Subcooled_CHF/dados/qqplot_distribuicoes.jpeg",width = 30,height = 10.51,units = "cm",res = 300)
plot(g)
dev.off()


library(gridExtra)

g = arrangeGrob(  p1,
  p2,
  nrow = 1,
  ncol = 2)

jpeg("../Subcooled_CHF/dados/dados_chf_zhao.jpeg",width = 30,height = 10.51,units = "cm",res = 300)
plot(g)
dev.off()

shapiro.test(base_sub$CHF)



```

